remote_theme: jekyll/minima
minima:
  skin: solarized-dark
  social_links:
     - { platform: linkedin,       user_url: "https://www.linkedin.com/in/ian-cooper" }

google_analytics: G-1Q7R1PRRVZ
